# Generated by Django 3.1.4 on 2021-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_designpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpattern',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
