# Generated by Django 3.1.4 on 2021-05-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0007_auto_20210514_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.IntegerField(blank=True, null=True)),
                ('sepm', models.IntegerField(blank=True, null=True)),
                ('fe', models.IntegerField(blank=True, null=True)),
                ('dp', models.IntegerField(blank=True, null=True)),
                ('ai', models.IntegerField(blank=True, null=True)),
                ('cn', models.IntegerField(blank=True, null=True)),
                ('acc', models.IntegerField(blank=True, null=True)),
                ('lib', models.IntegerField(blank=True, null=True)),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
