# Generated by Django 3.1.4 on 2021-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='final',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
