# Generated by Django 3.1.4 on 2021-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='year',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
