# Generated by Django 3.1.4 on 2021-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210512_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='sem',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
