# Generated by Django 3.1.4 on 2021-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
