# Generated by Django 3.1.4 on 2021-05-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_ex_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='student',
        ),
        migrations.DeleteModel(
            name='EX',
        ),
        migrations.DeleteModel(
            name='Studentinfo',
        ),
    ]
