# Generated by Django 3.1.4 on 2021-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='roll',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
